# LOCAL docker compose script

services:
  db:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: klinkdb # create database named klinkdb
      POSTGRES_HOST_AUTH_METHOD: trust  # Disables password requirement
    ports:
      - '5432:5432' # exposed for local development
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d klinkdb -U user" ]
      interval: 15s
      timeout: 60s
      retries: 5

  liquibase:
    build: 
      context: ./liquibase
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: >
      --url=jdbc:postgresql://db:5432/klinkdb
      --username=user
      --password=password
      --changeLogFile=/scripts/changelog.xml
      update
    restart: "no"

volumes:
  pgdata:
