# LOCAL docker compose script
version: '3.4'

services:
  db:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: klinkdb
      POSTGRES_HOST_AUTH_METHOD: trust  # Disables password requirement
    ports:
      - '5432:5432' # exposed for local development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exampleuser"]
      interval: 10s
      timeout: 5s
      retries: 5
