openapi: 3.0.0
info:
  title: Klink API
  description: API to manage Klinks
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api"
    description: Local server

paths:
  /klink:
    post:
      summary: "Create a new Klink."
      operationId: createKlink
      tags:
        - klink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKlinkPayload'
      responses:
        '201':
          description: "Collection created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Klink"
        '502':
          description: "Error."
  /klink/query-existing:
    post:
      summary: "Query existing klinks by ID."
      operationId: queryExisting
      tags:
        - klink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryExistingPayload"
      responses:
        '200':
          description: "Collection of klink IDs."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Klink'
        '502':
          description: "Error."
  /klink/{klinkId}:
    get:
      summary: "Get a klink by id."
      operationId: getKlink
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
      responses:
        '200':
          description: 'Collection retrieved.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Klink"
        '502':
          description: 'Error'
    patch:
      summary: "Update a klink by id."
      operationId: updateKlink
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchKlinkPayload"
        required: true
      responses:
        '200':
          description: 'Updated klink.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Klink"
        '502':
          description: 'Error'
    delete:
      summary: "Delete a klink by id."
      operationId: deleteKlink
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'Collection deleted'
        '502':
          description: 'Error'
  /klink/{klinkId}/urls:
    get:
      summary: "Get klink short urls designed for sharing."
      operationId: getKlinkShortUrl
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
      responses:
        '200':
          description: 'Related klink short url.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KlinkShortUrl"
        '502':
          description: 'Error'
  /klink/{klinkId}/entries:
    post:
      summary: "Add a new entry to a Klink."
      operationId: createKlinkEntry
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/KlinkEntry"
      responses:
        '200':
          description: "Klink entry created."
        '502':
          description: "Error."
    delete:
      summary: "Delete entries from a Klink."
      operationId: deleteKlinkEntries
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: read_key
          schema:
            type: string
          required: true
        - in: query
          name: write_key
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/KlinkEntry"
      responses:
        '204':
          description: "Klink entries deleted."
        '502':
          description: "Error."
  /klink/{klinkId}/sync:
    post:
      summary: "Synchronize a collection by ID."
      operationId: syncKlink
      tags:
        - klink
      parameters:
        - in: path
          name: klinkId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Klink'
      responses:
        '200':
          description: "Sync successful."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KlinkSyncStatus"
        '502':
          description: "Error."

components:
  schemas:
    Klink:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "Collection Name"
        readKey:
          type: string
          example: "j13c4in4"
          description: "Randomly generated alphanumeric sequece of length 8."
        writeKey:
          type: string
          example: "j13c4in4"
          description: "Randomly generated alphanumeric sequece of length 8."
        description:
          type: string
          example: "Links to random youtube videos."
        updatedAt:
          type: integer
          format: int64
          example: "1735127917 Unix Time."
        entries:
          type: array
          items:
            $ref: "#/components/schemas/KlinkEntry"
      required:
        - id
        - name
        - entries
        - updatedAt
        - readKey
        - writeKey
    KlinkShortUrl:
      type: object
      properties:
        url:
          type: string
          example: "https://x.drbros.tech/asdfg"
      required:
        - url
    PatchKlinkPayload:
      type: object
      properties:
        name:
          type: string
          example: "Collection Name"
        description:
          type: string
          example: "Links to random youtube videos."
      required:
        - name
    KlinkEntry:
      type: object
      properties:
        value:
          type: string
          description: "URL value unique by collection."
        title:
          type: string
          description: "URL title parsed from OpenGraph data"
        description:
          type: string
          description: "URL description parsed from OpenGraph data"
      required:
        - value
    CreateKlinkPayload:
      type: object
      properties:
        name:
          type: string
          description: "Collection name."
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        description:
          type: string
          description: "Collection description."
        entries:
          type: array
          items:
            $ref: "#/components/schemas/KlinkEntry"
      required:
        - name
        - id
        - entries
    KlinkSyncStatus:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/SyncStatus"
      required:
        - status
    SyncStatus:
      type: string
      enum:
        - IN_SYNC
        - OUT_OF_SYNC
    SyncPersistenceData:
      type: object
      properties:
        key:
          type: string
          description: "Klink id - UUID as string."
        newValue:
          type: string
          description: "Stringified JSON value of type List-KlinkEntryApiDto-."
        timeStamp:
          type: integer
          format: int64
          description: "Unix timestamp."
        url:
          type: string
          description: "Can be ignored."
      required:
        - key
        - newValue
        - timeStamp
        - url
    QueryExistingPayload:
      type: object
      properties:
        klinks:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              readKey:
                type: string
            required:
              - id
              - readKey
      required:
        - klinks
